### ISSUE TITLE
Angular2 version

### ISSUE THREAD

**Issue by rodneyjoyce** [thisissoon/angular-addthis#24]
Hello,

I am upgrading my ng1 sites to ng2 - do you have any plans to work on an Angular2 version of this? 

Thanks

**Comment by edoparearyee** [comment]
Hi @rodneyjoyce, unfortunately at the moment we don't have any plans to port this over to angular 2 due to a busy work load, maybe sometime in the future (but not sure when). 

However I would imagine that it wouldn't take too long or be too difficult to take the current code and logic and create a simple angular 2 component that would replicate this module.

**Comment by Chethannp** [comment]
Hey @rodneyjoyce did you figure out a way for this ? I badly need it working on my ionic angular 4 project :(

**Comment by alwinrichard1** [comment]
Hi @edoparearyee,  Is there any updates on Angular 2+ 'addthis' plugin? We are migrating our application to Angular 6.

**Comment by edoparearyee** [comment]
@alwinrichard1 sorry we still don't have any plans to update this library and most likely won't do as we no longer have a need for it. 

I would recommend simply taking the existing code [here](https://github.com/thisissoon/angular-addthis/blob/master/app/js/addthis.js), creating a new directive or component in the latest angular and update as needed.
